# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: cmd /c dotnet publish -a x64 --ucr true | dir .           
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: bin\
        compression-level: 9 
        retention-days: 90
